apiVersion: predoxy.achetronic.com/v1beta1
kind: Config
metadata:
  name: sample-proxy
spec:
  # Parameters related to networking capabilities
  listener:
    protocol: tcp
    host: 0.0.0.0
    port: 6381
  backend:
    host: localhost
    port: 6379

  # Parameters to configure plugins used to process messages and manage
  # Be careful here because the plugins are used following the list arrangement
  pipelines:
    plugins:
      - name: do-nothing
        path: do-nothing.so

    # The following lists TODO
    onReceive:
      - do-nothing
    onResponse:
      - do-nothing
